name: prayertime
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+9

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  adhan: ^2.0.0
  flutter_google_places: ^0.3.0
  location: ^5.0.3
  adhan_dart: ^1.0.8
  timezone: ^0.9.0
  geolocator: ^10.1.0
  shared_preferences: ^2.0.15
  email_validator: ^2.0.1
  datetime_picker_formfield: ^2.0.0
  fluttertoast: ^8.0.9
  google_maps_flutter: ^2.2.3
  awesome_dialog: ^3.0.2
  geocoding: ^2.0.5
  country_state_city_picker: ^1.2.8
  image_picker: ^1.0.7
  progress_state_button: ^1.0.4
  flutter_native_splash: ^2.2.7
  hidable: ^1.0.3
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  line_icons: ^2.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hijri: ^3.0.0
  city_pickers: ^1.1.0
  flutter_qiblah: ^2.1.0
  permission_handler: ^11.2.0
  audioplayers: ^5.2.1
  file_picker: ^5.2.5
  flutter_svg: ^2.0.9
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  device_info_plus: ^8.0.0
  eva_icons_flutter: ^3.1.0
  photo_view: ^0.14.0
  get: ^4.1.4
  flutter_typeahead: ^5.1.0
  firebase_database: ^10.0.10
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  wakelock: ^0.6.2
  country_pickers: ^2.0.0
  home_widget: ^0.4.1
  workmanager: ^0.5.0
  maps_launcher: ^2.2.0
  android_alarm_manager_plus: ^3.0.4
  pointer_interceptor: ^1.0.0
  country_code_picker: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_gen_runner: ^5.3.1

dependency_overrides:
  pointer_interceptor: ^0.10.1+2  # Version la plus récente
  pointer_interceptor_platform_interface:
    git:
      url: https://github.com/flutter/packages.git
      path: packages/pointer_interceptor/pointer_interceptor_platform_interface
      ref: main

flutter:
  uses-material-design: true
  generate: true  # <-- Ajoutez cette ligne


  assets:
    - images/
    - assets/

  fonts:
    - family: YourFontFamily
      fonts:
        - asset: fonts/YourFont-Regular.ttf
        - asset: fonts/YourFont-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  image_path: "images/logoPt.png"

flutter_native_splash:
  color: "#ffffff"
  image: "images/logoPt.png"