// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwoyjzH2BU9kJNx2rDMvdbqo-se6awws8',
    appId: '1:219143338185:android:5ada9edb4305c1739bb518',
    messagingSenderId: '219143338185',
    projectId: 'expopharma-20c26',
    databaseURL: 'https://expopharma-20c26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'expopharma-20c26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0sUvhB3WCTAAWBHB5rqWTCz_ynXYD00s',
    appId: '1:219143338185:ios:4ba4a4bba1591b859bb518',
    messagingSenderId: '219143338185',
    projectId: 'expopharma-20c26',
    databaseURL: 'https://expopharma-20c26-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'expopharma-20c26.appspot.com',
    iosClientId: '219143338185-0mi8tp9qe68mle6t4dn6g0i4v9455em6.apps.googleusercontent.com',
    iosBundleId: 'com.example.prayertime',
  );
}
